{"name": "Creation User Clone Error", "status": "passed", "start": 1727809271206, "stop": 1727809271868, "uuid": "4720196c-a35c-4253-bbe4-4b561de8ee60", "historyId": "06bfc9d0d8d5580f896a5a2211097735", "testCaseId": "06bfc9d0d8d5580f896a5a2211097735", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_clone_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "WIN-B95O9QQ3RDO"}, {"name": "thread", "value": "23340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}